In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
np.save("data.npy", arr)

In [2]:
loaded_arr = np.load("data.npy")
print(loaded_arr)

[1 2 3 4 5]


## Write a NumPy program that saves a large NumPy array to a compressed .npz file and then reads it back into a NumPy array.

In [3]:
data_array = np.random.rand(1000, 1000)

compressed_file_path = 'data_compressed.npz'

np.savez_compressed(compressed_file_path, data_array=data_array)

loaded_data = np.load(compressed_file_path)
loaded_array = loaded_data['data_array']

print("Original NumPy Array:")
print(data_array)

print("\nLoaded NumPy Array from Compressed .npz File:")
print(loaded_array)

Original NumPy Array:
[[0.69532919 0.13969966 0.30861405 ... 0.67522995 0.52167421 0.35574677]
 [0.28664514 0.0896239  0.19035305 ... 0.6070947  0.37689509 0.32978025]
 [0.05853312 0.69001282 0.74719465 ... 0.85032722 0.99325712 0.30731676]
 ...
 [0.45583198 0.21217935 0.56987883 ... 0.4275382  0.69015015 0.33829215]
 [0.91068948 0.20341422 0.41123175 ... 0.88437501 0.78734006 0.48021566]
 [0.85077175 0.86512563 0.63638979 ... 0.52520972 0.80861157 0.45218359]]

Loaded NumPy Array from Compressed .npz File:
[[0.69532919 0.13969966 0.30861405 ... 0.67522995 0.52167421 0.35574677]
 [0.28664514 0.0896239  0.19035305 ... 0.6070947  0.37689509 0.32978025]
 [0.05853312 0.69001282 0.74719465 ... 0.85032722 0.99325712 0.30731676]
 ...
 [0.45583198 0.21217935 0.56987883 ... 0.4275382  0.69015015 0.33829215]
 [0.91068948 0.20341422 0.41123175 ... 0.88437501 0.78734006 0.48021566]
 [0.85077175 0.86512563 0.63638979 ... 0.52520972 0.80861157 0.45218359]]
