In [1]:
import numpy as np

In [6]:
arr2D = np.array([[10, 20, 30], [40, 50, 60]])
rows = np.array([0, 1])
cols = np.array([2, 1])
print(arr2D)
print(arr2D[rows, cols])

[[10 20 30]
 [40 50 60]]
[30 50]


In [11]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])
arr > 25

[30 40 50]


array([False, False,  True,  True,  True])

# Write a  NumPy program that creates a 3D NumPy array and uses boolean indexing to set elements that meet a condition to a new value.

In [26]:
array_3d = np.random.randint(0, 100, size=(3,3,3))
array_3d

array([[[63,  2, 63],
        [15, 52,  8],
        [80, 88, 36]],

       [[ 0, 82, 40],
        [46, 35, 47],
        [57,  2, 49]],

       [[11, 42, 46],
        [34, 96, 81],
        [41, 75, 95]]])

In [27]:
array_3d[array_3d > 70]

array([80, 88, 82, 96, 81, 75, 95])

In [28]:
array_3d > 70

array([[[False, False, False],
        [False, False, False],
        [ True,  True, False]],

       [[False,  True, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False,  True,  True],
        [False,  True,  True]]])

In [29]:
array_3d[array_3d > 70] = -1

In [30]:
array_3d

array([[[63,  2, 63],
        [15, 52,  8],
        [-1, -1, 36]],

       [[ 0, -1, 40],
        [46, 35, 47],
        [57,  2, 49]],

       [[11, 42, 46],
        [34, -1, -1],
        [41, -1, -1]]])