In [1]:
import numpy as np

In [6]:
arr2D = np.array([[10, 20, 30], [40, 50, 60]])
rows = np.array([0, 1])
cols = np.array([2, 1])
print(arr2D)
print(arr2D[rows, cols])

[[10 20 30]
 [40 50 60]]
[30 50]


In [11]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])
arr > 25

[30 40 50]


array([False, False,  True,  True,  True])

# Write a  NumPy program that creates a 3D NumPy array and uses boolean indexing to set elements that meet a condition to a new value.

In [22]:
array_3d = np.random.randint(0, 100, size=(3,3,3))
array_3d

array([[[72, 85, 43],
        [26, 98, 71],
        [97,  7, 44]],

       [[36, 70, 41],
        [46, 71, 14],
        [71, 34, 67]],

       [[25, 72, 27],
        [49, 76, 97],
        [18, 85, 40]]])

In [23]:
array_3d[array_3d > 70] = -1

In [24]:
array_3d

array([[[-1, -1, 43],
        [26, -1, -1],
        [-1,  7, 44]],

       [[36, 70, 41],
        [46, -1, 14],
        [-1, 34, 67]],

       [[25, -1, 27],
        [49, -1, -1],
        [18, -1, 40]]])