In [1]:
import numpy as np

In [8]:
names = np.array(["Alice", "Bob", "Charlie", "Alice", "Bob"])
scores = np.array([90, 85, 95, 88, 92])

sorted_indices = np.lexsort((names, scores))
sorted_indices


array([1, 3, 0, 4, 2], dtype=int64)

In [9]:
sorted_names = names[sorted_indices]

In [10]:
sorted_names

array(['Bob', 'Alice', 'Alice', 'Bob', 'Charlie'], dtype='<U7')

In [11]:
sorted_scores = scores[sorted_indices]

In [12]:
sorted_scores

array([85, 88, 90, 92, 95])

In [16]:
arr2D = np.array([[10, 20, 30], [40, 50, 5]])

print(np.argmax(arr2D, axis=0))
print(np.argmin(arr2D, axis=0))
print(np.argmax(arr2D, axis=1))
print(np.argmin(arr2D, axis=1))

[1 1 0]
[0 0 1]
[2 1]
[0 2]


# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [23]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]
students = np.array(students_details, dtype=data_type)
students

array([(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
       (b'Pit', 5, 40.11)],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

In [22]:
print(students)

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]


In [26]:
print(np.sort(students, order="height"))

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [28]:
print(np.sort(students, order="class"))

[(b'James', 5, 48.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)
 (b'Nail', 6, 52.5 )]


In [30]:
print(np.sort(students, order="name"))

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]


In [35]:
print(np.sort(students, order=["class", "height"]))

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 45.5 )]


### Same Output using lexsort method but upper one is easy to understand

In [34]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 45.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]

# Create structured NumPy array
students = np.array(students_details, dtype=data_type)

# Extract columns (keys) correctly
class_column = students['class']  # Extract 'class' field
height_column = students['height']  # Extract 'height' field

# Pass the fields correctly to np.lexsort()
sorted_indices = np.lexsort((height_column, class_column))

# Apply sorting
sorted_students = students[sorted_indices]

print(sorted_students)

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 45.5 )]


In [38]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

print(student_id)
indices = np.argsort(student_id)
indices

[1023 5202 6230 1671 1682 5241 4532]


array([0, 3, 4, 6, 1, 5, 2], dtype=int64)

In [52]:
nums = np.array([70, 20, 30, -11, 60, 50, 40])
print(np.partition(nums, 3))

[ 20 -11  30  40  60  50  70]
