In [1]:
import numpy as np

In [6]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])

In [7]:
x

array([-1, -4,  0,  2,  3,  4,  5, -6])

In [8]:
x[x<0] = 0

In [9]:
x

array([0, 0, 0, 2, 3, 4, 5, 0])

In [10]:
arra_data = np.arange(0, 36).reshape((6, 6))

In [11]:
arra_data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
arra_data[[2, 4], ::2]

array([[12, 14, 16],
       [24, 26, 28]])

# Write a NumPy program to get the row numbers in a given array where at least one item is larger than a specified value.

In [29]:
num = np.arange(36)

num = np.reshape(num, [4, 9])

In [30]:
num

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [31]:
num[num > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [27]:
num[num > 10] = 0

In [28]:
num

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [32]:
num[num < 10] = 0

In [33]:
num

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [35]:
result = np.where(np.any(num> 10, axis=1))

In [36]:
result

(array([1, 2, 3], dtype=int64),)

# Write a Numpy program to test whether numpy array is faster than Python list or not.

In [37]:
import time 
import numpy as np 

SIZE = 200000

list1 = range(SIZE)
list2 = range(SIZE)
arra1 = np.arange(SIZE)
arra2 = np.arange(SIZE)

start_list = time.time()  # Marking the start time
result = [(x, y) for x, y in zip(list1, list2)]  # Aggregating elements from 'list1' and 'list2' using list comprehension
print("Time to aggregate elements from each of the iterables:")
print("List:")
print((time.time() - start_list) * 1000)  # Printing the execution time in milliseconds

# Measuring the time taken to add NumPy arrays element-wise
start_array = time.time()  # Marking the start time
result = arra1 + arra2  # Performing element-wise addition on 'arra1' and 'arra2' using NumPy
print("NumPy array:")
print((time.time() - start_array) * 1000)

Time to aggregate elements from each of the iterables:
List:
69.81587409973145
NumPy array:
12.010335922241211
