# Write a NumPy program to create a 3x3 array with random values and calculate the pairwise Euclidean distance between each pair of rows.

In [5]:
import numpy as np
from scipy.spatial import distance

array = np.random.randint(1, 50, 9).reshape(3, 3)

# Print the original array
print("Original Array:\n", array)

# Calculate pairwise Euclidean distances between each pair of rows
pairwise_distances = distance.cdist(array, array, 'euclidean')

# Print the pairwise distances
print("Pairwise Euclidean distances between each pair of rows:\n", pairwise_distances)

Original Array:
 [[16 46 11]
 [14 36 48]
 [49 46  8]]
Pairwise Euclidean distances between each pair of rows:
 [[ 0.         38.37968212 33.13608305]
 [38.37968212  0.         54.08326913]
 [33.13608305 54.08326913  0.        ]]


# Check if any element in a 1D array is non-zero.

In [6]:
arr = np.array([0, 0, 0, 1, 0])
any_nonzero = np.any(arr != 0)
print(any_nonzero)

True


# Create a 2D array with random integers and replace all values greater than a certain threshold with that threshold.

In [7]:
matrix = np.random.randint(0, 100, size=(3, 4))
threshold = 75
matrix[matrix > threshold] = threshold
print(matrix)

[[63 34 52 49]
 [75 59 75 38]
 [61 75 63 74]]
