In [1]:
import numpy as np

# DateTime
## Write a NumPy program to find the number of weekdays in March 2017.

In [2]:
print(np.busday_count("2017-03", "2017-04"))

23


In [4]:
print(np.busday_count("2025-01", "2025-02"))

23


In [7]:
print(np.busday_count("2025-01-06", "2025-02-01"))

20


# Write a  NumPy program to get the dates of yesterday, today and tomorrow.

In [12]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)

today = np.datetime64('today', 'D')
print("Today: ", today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow) 

Yestraday:  2025-01-29
Today:  2025-01-30
Tomorrow:  2025-01-31


# String
## Write a NumPy program to count a given word in each row of a given array of string values.

In [13]:
str1 = np.array([['Python','NumPy','Exercises'],
                 ['Python','Pandas','Exercises'],
                 ['Python','Machine learning','Python']])

In [14]:
print(np.char.count(str1, 'Python')) 

[[1 0 0]
 [1 0 0]
 [1 0 1]]


In [16]:
row_counts = np.sum(np.char.count(str1, "Python"), axis=1)

In [17]:
row_counts

array([1, 1, 2])