# Universal Functions
## Write a NumPy program that creates a 2D NumPy array and a 1D array. Use the np.add ufunc to add the 1D array to each row of the 2D array.

In [3]:
import numpy as np

array_2d = np.random.randint(0, 10, size=(3, 3))

array_1d = np.random.randint(0, 10, size=3)

result_array = np.add(array_2d, array_1d)

print(array_2d)
print(array_1d)
print(result_array)

[[1 5 3]
 [9 0 4]
 [7 4 7]]
[7 5 7]
[[ 8 10 10]
 [16  5 11]
 [14  9 14]]


# Masked Array
## Write a NumPy program to replace all masked values in a masked array with the mean of the unmasked elements.

In [4]:
data = np.array([1, 2, 3, np.nan, 5, 6, np.nan, 8, 9, 10])

mask = np.isnan(data)
masked_array = np.ma.masked_array(data, mask=mask)

mean_value = masked_array.mean()

filled_array = masked_array.filled(mean_value)

print("Original Array:")
print(data)

print("\nMasked Array:")
print(masked_array)

print("\nFilled Array (masked values replaced with mean):")
print(filled_array)

Original Array:
[ 1.  2.  3. nan  5.  6. nan  8.  9. 10.]

Masked Array:
[1.0 2.0 3.0 -- 5.0 6.0 -- 8.0 9.0 10.0]

Filled Array (masked values replaced with mean):
[ 1.   2.   3.   5.5  5.   6.   5.5  8.   9.  10. ]
