# Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array.

In [5]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

print("\nCumulative sum of the elements along a given axis:")
r = np.cumsum(x)
print(r)

print("\nSum over rows for each of the 3 columns:")
r = np.cumsum(x, axis=0)
print(r)

print("\nSum over columns for each of the 2 rows:")
r = np.cumsum(x, axis=1)
print(r) 

[[1 2 3]
 [4 5 6]]

Cumulative sum of the elements along a given axis:
[ 1  3  6 10 15 21]

Sum over rows for each of the 3 columns:
[[1 2 3]
 [5 7 9]]

Sum over columns for each of the 2 rows:
[[ 1  3  6]
 [ 4  9 15]]


In [6]:
x.flatten()

array([1, 2, 3, 4, 5, 6])