# Write a NumPy program to compute the determinant of an array.

In [7]:
import numpy as np

a = np.array([[1,2],[5,4]])

det = np.linalg.det(a)
print(a)
det

[[1 2]
 [5 4]]


-6.0

# Write a NumPy program to compute the inverse of a given matrix.

In [8]:
inv = np.linalg.inv(a)

In [9]:
inv

array([[-0.66666667,  0.33333333],
       [ 0.83333333, -0.16666667]])

In [10]:
a

array([[1, 2],
       [5, 4]])

In [11]:
np.trace(a)

5